### ISSUE TITLE
[Enhancement proposal] Add support to delete coverage report from VS

### ISSUE THREAD

**Issue by malickf** [atlaste/CPPCoverage#27]
Hi, 
Thank you for your work, it is a very useful and easy to use extension !
I would like to suggest you a minor improvement : to add a menu button to be able to delete the Coverage file from Visual Studio. Indeed once codecoverage is run and analysed, we may want to remove all the colours and reports. It [seems ](https://github.com/atlaste/CPPCoverage/issues/25#issuecomment-506734817) the only way is to modify the code or to delete manually the coverage report file. I think it will be very nice if we could do it right from the menu bar in VS.  
Thanks again !
Malick

**Comment by atlaste** [comment]
Yes, we agree :-) 
What we do is right click on the code window, and click 'show coverage' - that basically toggles all the highlighting. I'm not 100% sure if it's also in the version we already have online.
We're also currently working on having multiple coverage runs in the same solution. That's a bit tougher though.

**Comment by malickf** [comment]
Great !! I wasn't aware of this right-click toggle button. I just tested it on my platform (VS 2019 with CPP Code Coverage 2.31) and it works perfectly. I think my proposal is useless thanks to this magic feature !

**Comment by atlaste** [comment]
Good. And thanks for confirming it; we're working on a major rebuild, so it's often hard to track what changed and what didn't... Either ways, I'll close the ticket.
