### ISSUE TITLE
Visual Studio 2022

### ISSUE THREAD

**Issue by nickledeg** [atlaste/CPPCoverage#39]
I am firmly hooked on CPPCoverage. Are there any plans to create a version for VS2022?

**Comment by atlaste** [comment]
Oh pfew, not really. I tried making the addin compatible with future versions as-is, but apparenly MS seems hell bent on breaking compatibility every single version... The visx seems to be the main culprit, i wouldnt be surprised if you can just run it as is.

**Comment by nickledeg** [comment]
ok. Thanks. I have a go

**Comment by atlaste** [comment]
Let me know if it works please, there are bound to be more people that are wondering.

**Comment by nickledeg** [comment]
I am sure it can be made to work, however this is not my area of expertise. This seems to be a good instructional video: https://www.youtube.com/watch?v=1139WJak1-w I would need to find some to get myself up to speed to do this.

**Comment by atlaste** [comment]
I quickly went through the video, it seems like the steps to take. I just hope it's the complete picture; they seem to be hell bent on changing the API every time...

**Comment by nickledeg** [comment]
I have had a go at doing this but all I managed to do was create a mess! I therefore give my apologies and will wait for a more knowledgeable programmer to take up the challenge. As well as the video above we also have this article. https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension

**Comment by PatHa9** [comment]
I got it working in VS2022. Changes are only in project files (no code change). I did not try to have the same project working for both vs2022 and previous version so not sure how to share this with you. I tried creating a vs2022proto branch but I don't have rights to create a new branch. Let me know if you are interested and how I should proceed to share this with you.

**Comment by nickledeg** [comment]
Thanks very much! I look forward to trying it out. You could try forking the repo, unless @atlaste has a better idea.

**Comment by PatHa9** [comment]
[PatHa9](https://github.com/PatHa9/CPPCoverageVs2022)
Not ready to be merged as it only builds a Vs2022 version and I did not test much. Providing it for you if you want to use it in VS2022 and for @atlaste if he wants to complete the work.

**Comment by nickledeg** [comment]
@PatHa9. I am very grateful. I will give it a go

**Comment by PatHa9** [comment]
You are welcomed. Forgot to mention that you need to get the vs2022Proto branch.

**Comment by seppy61** [comment]
I installed the vsix in Visual Studio 2022 Version 17.8.3 but there is an error when activating any of the functions. Method not found: EnvDTE.Document EnvDTE._DTE.get_ActiveDocument() at NubiloSoft.CoverageExt.CodeRendering.Coverage.GetActiveFilename()...

**Comment by jgshumate1** [comment]
@atlaste Is there an issue with VS2022?  Or should this be closed since it works for VS2022 now?

**Comment by atlaste** [comment]
> @atlaste Is there an issue with VS2022? Or should this be closed since it works for VS2022 now?

You're right, this should just beclosed.
