### ISSUE TITLE
Coverage report window is empty.

### ISSUE THREAD

**Issue by LinArcX** [atlaste/CPPCoverage#40]
Here is my system configuration:

Windows: 10
Test library: GoogleTest(latest version)
VisualStudio: 2019 Community

And here is the steps to generate coverage report:
1. Right click on the project and run: "Run Tests"
2. Open a .cpp file.
3. Go to: Toos --> Coverage report.

It's empty!
Also i can't see any impact of CPPCoverage on my current file!

This is the output of CodeCoverage from the output window:
> Calculating code coverage...
Loading process: D:\workspace\c++\cpp\projects\active\tdd_kata\build\windows\debug\x64\tdd_kata.exe... [Symbols loaded]
Loading: C:\Windows\System32\ntdll.dll... 
[No symbols available: The request is not supported.]
Loading: C:\Windows\System32\kernel32.dll... 
[No symbols available: The request is not supported.]
Loading: C:\Windows\System32\KernelBase.dll... 
[No symbols available: The request is not supported.]
Patching IsDebuggerPresent() in KernelBase.dll
Running main() from D:\workspace\c++\cpp\projects\active\libs\googletest\googletest\src\gtest_main.cc
[==========] Running 8 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 6 tests from CalcStatTests
[ RUN      ] CalcStatTests.ThrowStdInvalidArgumentWhenCallMinimumValueWithAnEmptyArray
[       OK ] CalcStatTests.ThrowStdInvalidArgumentWhenCallMinimumValueWithAnEmptyArray (0 ms)
[ RUN      ] CalcStatTests.ReturnMinimumValueWhenPassAnArrayWithOneElement
[       OK ] CalcStatTests.ReturnMinimumValueWhenPassAnArrayWithOneElement (0 ms)
[ RUN      ] CalcStatTests.ReturnMinimumValueWhenPassAnArrayWithTwoElements
[       OK ] CalcStatTests.ReturnMinimumValueWhenPassAnArrayWithTwoElements (0 ms)
[ RUN      ] CalcStatTests.ReturnMinimumValueWhenPassAnArrayWithThreeElements
[       OK ] CalcStatTests.ReturnMinimumValueWhenPassAnArrayWithThreeElements (0 ms)
[ RUN      ] CalcStatTests.ReturnMinimumValueWhenPassAnArrayWithEightElements
[       OK ] CalcStatTests.ReturnMinimumValueWhenPassAnArrayWithEightElements (0 ms)
[ RUN      ] CalcStatTests.ThrowStdInvalidArgumentWhenCallMaximumValueWithAnEmptyArray
[       OK ] CalcStatTests.ThrowStdInvalidArgumentWhenCallMaximumValueWithAnEmptyArray (0 ms)
[----------] 6 tests from CalcStatTests (0 ms total)
[----------] 1 test from CheckoutTests
[ RUN      ] CheckoutTests.CanCreateInstanceOfCheckoutClass
[       OK ] CheckoutTests.CanCreateInstanceOfCheckoutClass (0 ms)
[----------] 1 test from CheckoutTests (0 ms total)
[----------] 1 test from ManhatanDistanceTests
[ RUN      ] ManhatanDistanceTests.CanCreateInstanceOfCheckoutClass
[       OK ] ManhatanDistanceTests.CanCreateInstanceOfCheckoutClass (0 ms)
[----------] 1 test from ManhatanDistanceTests (0 ms total)
[----------] Global test environment tear-down
[==========] 8 tests from 3 test suites ran. (1 ms total)
[  PASSED  ] 8 tests.
Loading: C:\Windows\System32\kernel.appcore.dll... 
[No symbols available: The request is not supported.]
Loading: C:\Windows\System32\msvcrt.dll... 
[No symbols available: The request is not supported.]
Loading: C:\Windows\System32\rpcrt4.dll... 
[No symbols available: The request is not supported.]
Process exited with code: 0.
Gathering profile data of 0 sources...
Filtering post-process notifications...
Writing coverage report...done.
Updating coverage results from: D:\workspace\c++\cpp\projects\active\tdd_kata\windows\CodeCoverage.cov

**Comment by atlaste** [comment]
That's usually a sign of not compiling it correctly. See the main page, section "getting started".
