### ISSUE TITLE
LoadSettingsFromStorage: FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by MAntoniak** [atlaste/CPPCoverage#44]
Hello,
I have a problem reading data into the GeneralOptionPageGrid class via the LoadSettingsFromStorage method. I am getting an error:
```
System.Exception: '255, 207, 184 is not a valid value for Int32.'
FormatException: Input string was not in a correct format.
```

The GeneralOptionPageGrid dialog box uses a CustomColorConverter object to write and read values of individual colors. When loading data (LoadSettingsFromStorage), the CustomColorConverter class uses the ConvertFrom method with CultureInfo set to CurrentCulture. Saving the data (SaveSettingsToStorage) is done by using the ConvertTo method with the CultureInfo set to InvariantCulture. These values affect how the color value is written and read. In my case, the CurrentCulture value is “en-PL” and the separator of the individual ARGB values is a semicolon. In the case of InvariantCulture, the separator is a comma.

The solution may be to write the data explicitly using CultureInfo.CurrentCulture:

```
index 69c0f71..583ff8a 100644
--- a/CoverageExt/GeneralOptionPageGrid.cs
+++ b/CoverageExt/GeneralOptionPageGrid.cs
@@ -2,6 +2,7 @@
 using System;
 using System.ComponentModel;
 using System.Drawing;
+using System.Globalization;
 
 namespace NubiloSoft.CoverageExt
 {
@@ -9,7 +10,12 @@ namespace NubiloSoft.CoverageExt
     /// Dumbfounded why we need this, since it effectievely shouldn't do anything else but even 
     /// using [TypeConverter(typeof(ColorConverter))] doesn't work.
     /// </summary>
-    class CustomColorConverter : ColorConverter { }
+    class CustomColorConverter : ColorConverter {
+        public override object ConvertTo( ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType )
+        {
+            return base.ConvertTo( context, CultureInfo.CurrentCulture, value, destinationType );
+        }
+    }
 
     [System.ComponentModel.DesignerCategory("")]
     public class GeneralOptionPageGrid : DialogPage
-- 
```

If this is an acceptable solution I can do PR. What could be other alternative solutions?

My Visual Studio version is 17.10.4.

**Comment by atlaste** [comment]
Seems reasonable, just make it a PR. The VS extension just seem to be a gift that keeps on giving.

**Comment by MAntoniak** [comment]
I'm not familiar with vsix project, so one more question. What about update VS extension? What happens during an update to the data stored in storage? Are they being reset? I would like to avoid the case where after the update someone's VS extension stops working because the way of reading data has changed.
